app:
  build: .
  links:
    - mongo
    - postgres
  volumes:
    - ./app:/application/app
    - ./config:/application/config
    - ./public:/application/public
    - ./db:/application/db
  ports:
    - '1337:1337'
  command: nodemon app/server.js
  environment:
    - 'DATABASE_URL=postgresql://pguser:pgpass@postgres:5432/sfez-development'
    - MONGO_URL=mongodb://mongo:27017/sfez
    - NODE_ENV=development
    - PORT=8080
mongo:
  image: mongo:3.3
pgadmin:
  image: postgres:9.5
  command: tail -f /dev/null
  links:
    - postgres
  environment:
    - PGUSER=pguser
    - PGPASSWORD=pgpass
    - PGHOST=postgres
postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_USER=pguser
    - POSTGRES_PASSWORD=pgpass
